version: '3'

services:
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017

  theater_app:
    build: ./
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - mongo

volumes:
  mongodb-data: